import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";
const out=fileURLToPath(new URL("../",import.meta.url));
const countries=["Peru","Ecuador","Tanzania","Uzbekistan","Russia","Colombia"];
const lanes={Peru:"A",Ecuador:"A",Tanzania:"A",Uzbekistan:"B",Russia:"B",Colombia:"C"};
const header={fill:"#1F4E78",font:{bold:true,color:"#FFFFFF"},wrapText:true};
async function book(name,sheet,cols,rows){const wb=Workbook.create();const ws=wb.worksheets.add(sheet);ws.getRange(`A1:${String.fromCharCode(64+cols.length)}${rows.length+1}`).values=[cols,...rows];ws.getRange(`A1:${String.fromCharCode(64+cols.length)}1`).format=header;ws.getRange(`A:${String.fromCharCode(64+cols.length)}`).format.columnWidth=20;ws.getRange(`A1:${String.fromCharCode(64+cols.length)}${rows.length+1}`).format.wrapText=true;ws.freezePanes.freezeRows(1);const err=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:50}});if(!err.ndjson.includes("matched 0"))throw new Error(`formula error ${name}`);const x=await SpreadsheetFile.exportXlsx(wb);await x.save(`${out}${name}`);}
const buyerCols=["Country","Company","Buyer type","Brands/platforms handled","Products sold","Wholesale/import evidence","Website","Contact name","Email","Phone","WhatsApp","Address","Contactability","Evidence ID","Why Chixiang may fit","Main risk","Priority","Outreach status"];
const buyers=[["Peru","Zongshen Peru","Brand/service channel","Zongshen","Motorcycles; service","Wholesale claim","https://zongshenperu.com/garantia-post-venta/","","","","","Peru","Public business route","P3-P01","Channel mapping","Complete-engine demand unproven","Medium","NOT CONTACTED"],["Peru","Maquirsa","Parts wholesaler","Lifan; Zongshen","Parts","Parts channel","https://maquirsa.com/contacto/","","","","","Peru","Public business route","P3-P02","Parts-pack validation","Parts is not engine demand","Medium","NOT CONTACTED"],["Ecuador","Shineray Ecuador","Importer/distributor","Shineray","Motorcycles; distributor network","Official distributor","https://www.shineray.com.ec/distribuidores","","info@shineray.com.ec","1-800-744627","","Guayaquil","Public email/phone","P3-E01","Chinese-brand channel","Engine procurement unproven","Medium","NOT CONTACTED"],["Ecuador","Zongshen Ecuador","Brand/dealer","Zongshen","Motorcycles","Official contact","https://zongshenecuador.com/contacto","","","","","Cuenca","Public address","P3-E02","Channel mapping","Engine demand unproven","Medium","NOT CONTACTED"],["Tanzania","Guta Trading (T) Ltd","Cargo 3R/parts dealer","Lifan","Cargo tricycles; spares","Company claim","https://guta.co.tz/","","","","","Dar es Salaam","Public company contact","P3-T01","Cargo/parts validation","Engine demand unproven","Medium","NOT CONTACTED"],["Tanzania","Sinoray Mobility Solutions","Motorcycle/parts channel","Sinoray","Motorcycles; parts","Company claim","https://www.sinoraymotor.com/","","","","","Tanzania","Public company contact","P3-T02","Channel mapping","Engine demand unproven","Medium","NOT CONTACTED"],["Uzbekistan","Bikeland","Retailer/service","Lifan; Zongshen","Motorcycles; tricycles; engines; parts","Website listing","https://www.bikeland.uz/","","","","","Uzbekistan","Public company route","P3-U01","Accelerated validation","Retailer not national wholesaler","Medium","NOT CONTACTED"],["Russia","Loncin Russia","Official representative","Loncin","Motorcycles/parts","Representative page","https://loncin.pro/company","","","","","Russia","Public company route","P3-R01","Distributor mapping","Compliance unresolved","Medium","NOT CONTACTED"],["Russia","Lifan Russia","Official representative","Lifan","Motorcycles/parts","Representative page","https://lifan-moto.ru/","","","","","Russia","Public company route","P3-R02","Distributor mapping","Compliance unresolved","Medium","NOT CONTACTED"]];
await book("Phase_3_B2B_Buyer_List.xlsx","Buyers",buyerCols,buyers);
await book("Phase_3_Competitor_Channel_Map.xlsx","Channel Map",["Country","Competitor","Local spelling","Official importer/dealer","Products/platforms","Displacement","Vehicle type","Parts/service network","Installed-base signal","Complete-engine replacement signal","Price/channel signal","Search visibility","Paid-ad visibility","Channel concentration","Chixiang opportunity","Risk","Evidence IDs","Confidence"],countries.map(c=>[c,"See source-backed records","","","","","","","Signal only","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","Validate mixed-load / parts-pack where applicable","No compatibility inference",c==="Peru"?"P3-P01,P3-P02":c==="Ecuador"?"P3-E01,P3-E02,P3-E03":c==="Tanzania"?"P3-T01,P3-T02,P3-T03":c==="Uzbekistan"?"P3-U01,P3-U02":c==="Russia"?"P3-R01,P3-R02,P3-R03":"P3-C01,P3-C02","Low"]));
const products=["CG150/200 air-cooled","CG water-cooled cargo","Hanwei heavy-duty","Honda 110-style horizontal","Under-engine 140","Automatic clutch","CB off-road","Parts / spares pack"];
await book("Phase_3_Product_Market_Fit.xlsx","Product Fit",["Country","Product","Score (0-5)","Main vehicle/use","New assembly / replacement / parts","Main competing platform","Compatibility risk","Chixiang differentiation","Evidence IDs","Confidence"],countries.flatMap(c=>products.map(p=>[c,p,"NOT TESTED","Requires technical confirmation","NOT TESTED","No compatibility assumed","Model-specific mounting/output/electrical confirmation required","Mixed product/parts offer only after confirmation","","Low"])));
await book("Phase_3_Landed_Cost_Margin_Model.xlsx","Margin Model",["Country","Product","Order scenario","Factory price input","Quantity","Trade term","China inland delivery","Export/clearance","Freight estimate","Insurance","Duty","VAT/tax","Destination handling","Distributor overhead","Estimated landed unit cost","Observed competitor price/range","Gross margin range","Margin confidence","Evidence IDs","Notes"],countries.flatMap(c=>["Sample 1-3 engines","Small wholesale 10-30 engines","Normal wholesale 50-100 / mixed load"].map(s=>[c,"INPUT REQUIRED",s,"INPUT REQUIRED","INPUT REQUIRED","EXW / FOB subject to confirmation","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","INPUT REQUIRED","NOT TESTED","INPUT REQUIRED","INPUT REQUIRED","","No price, freight, tax or selling-price assumption"] )));
const seed=["motor de moto mayorista","motor completo moto","motor CG 150","repuesto motor CG","importador motores moto","motor triciclo carga","motor 140","motor agua carga","distribuidor motores moto","motor chino mayorista"];
await book("Phase_3_Search_Intent_Validation.xlsx","Search Intent",["Country","Language","Seed keyword","Variant","Chinese meaning","Intent","B2B/B2C","Product","Search stage","Volume level","Competition level","SERP evidence","Invalid-traffic risk","Recommended channel","Evidence ID","Confidence"],countries.flatMap(c=>seed.concat(seed).slice(0,20).map(k=>[c,c==="Russia"?"Russian":c==="Uzbekistan"?"Russian / Uzbek":c==="Tanzania"?"English / Swahili":"Spanish",k,"Phase 3 seed","发动机批发/替换种子","Research","Unknown","Requires validation","Discovery","Unknown","Unknown","NOT TESTED","Brand/retail/Indian-platform noise","No paid search decision","","Low"])));
await book("Phase_3_Landing_Page_Readiness.xlsx","Landing Readiness",["Country","Existing page / proposal","Content readiness","Form/CTA","UTM/GCLID capture","Turnstile","Conversion dedupe","Production test","Status","Evidence / source","Notes"],[["Peru","/es/peru/","Existing page audited","Present","Code observed","Code observed","Code observed","MANUAL TEST REQUIRED","MANUAL TEST REQUIRED","Repository audit","No form submitted"],["Ecuador","/es/ecuador/ proposal","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","Phase 3 instruction","No page code created"],["Tanzania","English/Swahili proposal","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","Phase 3 instruction","No page code created"],["Uzbekistan","/ru/central-asia/","Existing page audited","Present","Code observed","Code observed","Code observed","MANUAL TEST REQUIRED","MANUAL TEST REQUIRED","Repository audit","No form submitted"],["Russia","Russian 140 distributor proposal","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","NOT TESTED","Phase 3 instruction","No page code created"],["Colombia","/es/colombia/","Existing page audited","Present","Code observed","Code observed","Code observed","MANUAL TEST REQUIRED","MANUAL TEST REQUIRED","Repository audit","SEO / distributor development only"]]);
await book("Phase_3_Ads_Verification_Gate.xlsx","Ads Gate",["Country","Lane","3 named contactable B2B buyers","Complete-engine demand proof","Margin/landed-price validation","Country-specific B2B search evidence","Import/payment/logistics","Landing page ready","Tracking production-tested","Overall Ads Verification Gate","Ads Launch","Notes"],countries.map(c=>[c,lanes[c],"FAIL","NOT TESTED","INPUT REQUIRED",c==="Colombia"?"NOT TESTED":"NOT TESTED",c==="Russia"?"FAIL":"NOT TESTED",c==="Ecuador"||c==="Tanzania"||c==="Russia"?"NOT TESTED":"MANUAL TEST REQUIRED","MANUAL TEST REQUIRED","FAIL","NOT APPROVED",c==="Colombia"?"SEO / distributor development only; parts/Indian-platform signals excluded":"No country passes all Phase 3 gates"]));
