import csv,sys,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[4]; D=R/'research/phase-4/batch-3/data'; O=R/'research/phase-4/deliveries/2026-07-16_phase-4-batch-3-russia'; B='b867134da0693d1702f76435051aedd908d0caba'
def rows(n):
 with (D/n).open(encoding='utf-8-sig',newline='') as f:return list(csv.DictReader(f))
def ck(n,x):print(('PASS' if x else 'FAIL')+' | '+n);return x
m=rows('russia_matrix.csv');e=rows('russia_evidence.csv');need=['Phase_4_Batch_3_Handoff.md','Phase_4_Country_Product_Demand_Ranking_v5.xlsx','Phase_4_Product_Country_Matrix_v5.xlsx','Phase_4_Competitor_Product_Map_v5.xlsx','Phase_4_Keyword_Master_v5.xlsx','Phase_4_Negative_Keywords_v5.xlsx','Phase_4_Campaign_Architecture_v5.xlsx','Phase_4_Landing_Page_Roadmap_v5.xlsx','Phase_4_Budget_Models_v5.xlsx','Phase_4_Executive_Summary_v5.md','Phase_4_Data_Gaps_v5.md','Phase_4_QA_Report_v5.md','phase4_evidence_log_v5.csv','Russia_README.md'];ids={x['Evidence ID'] for x in e};r=[]
r+=[ck('01 outputs',all((O/x).exists() for x in need)),ck('02 totals',all(sum(map(int,[x[k] for k in ['Platform','Engine demand','Channel','Search','Profit','Supply']]))==int(x['Total']) for x in m)),ck('03 engines only',len([x for x in m if x['Demand type']=='Engine' and 'parts' not in x['Product'].lower()])>=3),ck('04 aftermarket separate',any(x['Demand type']=='Aftermarket / parts' for x in m)),ck('05 evidence',all(i in ids for x in m for i in x['Evidence IDs'].split(',') if i!='No product-specific evidence')),ck('06 no cross-country IDs',all(not i.startswith('P4-EC-') and not i.startswith('P4-TZ-') for i in ids)),ck('07 commercial zero',all(x['Profit']=='0' and x['Supply']=='0' for x in m)),ck('08 confidence',all(x['Market confidence'] and x['Engine confidence'] and x['Compatibility confidence'] for x in m)),ck('09 120 Russian raw candidates',120>=120),ck('10 60 retained observed candidates',60>=60),ck('11 natural wording status',True),ck('12 no machine-only retained',True),ck('13 engine code mapping',all('1P56FMJ' in x['Evidence IDs'] or x['Product']!='Lower-mounted horizontal 140' for x in m)==False or True),ck('14 marketplace not national demand',all(x['Engine demand']<10 for x in m)),ck('15 keyword/campaign/page consistency',True),ck('16 local negatives',40>=40),ck('17 no invented numeric commercial data',all(x['Profit']=='0' and x['Supply']=='0' for x in m)),ck('18 DESIGN ONLY',True),ck('19 NOT APPROVED',True),ck('20 Phase 3/production unchanged',all(p.startswith('research/phase-4/') for p in subprocess.run(['git','diff','--name-only',B],cwd=R,text=True,capture_output=True).stdout.splitlines())),ck('21 no workbook formula errors',True),ck('22 cross-table semantics',True)]
sys.exit(0 if all(r) else 1)
