import { fileURLToPath } from "node:url";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const root = fileURLToPath(new URL("../", import.meta.url));
const blue = { fill: "#1F4E78", font: { bold: true, color: "#FFFFFF" }, wrapText: true };
const products = [
  "CG125 air-cooled", "CG150 air-cooled", "CG175 air-cooled", "CG200 air-cooled", "CG250 air-cooled",
  "CG150–250 water-cooled cargo", "Tsunami water-cooled / dual-cooled", "Hanwei 200", "Hanwei 250", "Hanwei 300", "Hanwei 350",
  "Honda-style 110 horizontal", "Honda-style 125 horizontal", "Honda-style 130/140 horizontal", "Lower-mounted 140", "Automatic-clutch CG", "Automatic-clutch horizontal", "CB150/200/250 off-road", "EFI water-cooled", "Engine parts / spares pack"
];
const countryScores = {
  Peru: [55,78,40,82,68,52,25,25,35,20,15,25,30,25,15,25,15,35,20,76],
  Uzbekistan: [25,38,30,45,50,78,35,30,45,35,25,25,28,35,30,20,20,25,30,55]
};
const tiers = score => score >= 75 ? "A" : score >= 55 ? "B" : score >= 40 ? "C" : "D";
const fmt = score => score >= 70 ? "High" : score >= 45 ? "Medium" : "Low";
const peEvidence = "P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-04,P4-PE-05,P4-PE-06,P4-PE-07,P4-PE-08,P4-PE-09";
const uzEvidence = "P4-UZ-01,P4-UZ-02,P4-UZ-03,P4-UZ-04,P4-UZ-05,P4-UZ-06,P4-UZ-07";
function col(n) { let s=""; while(n){ const r=(n-1)%26; s=String.fromCharCode(65+r)+s; n=Math.floor((n-1)/26); } return s; }
async function book(name, sheet, headers, rows) {
  const wb = Workbook.create(); const ws = wb.worksheets.add(sheet); const last = col(headers.length);
  ws.getRange(`A1:${last}${rows.length + 1}`).values = [headers, ...rows];
  ws.getRange(`A1:${last}1`).format = blue;
  ws.getRange(`A:${last}`).format.columnWidth = 18;
  ws.getRange(`A1:${last}${rows.length + 1}`).format.wrapText = true;
  ws.freezePanes.freezeRows(1);
  const errors = await wb.inspect({ kind: "match", searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A", options: { useRegex: true, maxResults: 50 } });
  if (!errors.ndjson.includes("matched 0")) throw new Error(`Formula error in ${name}`);
  const output = await SpreadsheetFile.exportXlsx(wb); await output.save(`${root}${name}`);
}
function demandRows(country) {
  return products.map((product, i) => {
    const score = countryScores[country][i]; const pe = country === "Peru";
    const use = pe
      ? (product.includes("CG200") ? "cargo motorcycle / cargo trimoto; replacement and parts" : product.includes("CG150") ? "work motorcycle / passenger and cargo trimoto; replacement and parts" : product.includes("parts") ? "after-sales wholesale parts" : "research-only direction")
      : (product.includes("water-cooled cargo") ? "250 cc cargo tricycle; new vehicle / assembly signal" : product.includes("CG250") ? "cargo tricycle research direction" : product.includes("parts") ? "after-sales parts channel" : "research-only direction");
    const type = product.includes("parts") ? "Parts" : product.includes("water-cooled cargo") && !pe ? "New vehicle / assembly signal; replacement NOT TESTED" : "Complete-engine / replacement signal varies; verify before sale";
    const reason = pe
      ? (product === "CG200 air-cooled" ? "Complete CG200 cargo-engine listings plus cargo-trimoto and CG200 parts signals; no Chixiang fit inference." : product === "CG150 air-cooled" ? "150 cc trimoto, complete CG150 and wholesale parts signals; exact output/installation still requires confirmation." : product.includes("parts") ? "Wholesale CG125/150/200/250 parts catalogue is visible; parts demand is not complete-engine demand." : "No sufficient country-specific complete-engine proof; score is conservative.")
      : (product === "CG150–250 water-cooled cargo" ? "Multiple listed Loncin 250 cc water-cooled cargo tricycles; engine specification/output fit remains Factory specification required." : product === "Engine parts / spares pack" ? "Lifan engine catalogue and Loncin/Zongshen parts visibility; no complete-engine replacement inference." : "No sufficient country-specific product-demand proof; score is conservative.");
    return [country, product, score, tiers(score), type, use, reason, pe ? peEvidence : uzEvidence, fmt(score), product.includes("water-cooled cargo") || product.includes("Hanwei") || product.includes("EFI") ? "YES" : "MODEL-SPECIFIC"];
  });
}
const competitorRows = [
  ["Peru","Zonsen / Zongshen","Zonsen","150 cc trimoto; motorcycles; service/parts","150","Passenger/cargo trimoto and work use","Grupo Cayman / dealer network","Wholesale motorcycle and parts routes visible","Network stated by brand","NOT TESTED","NOT TESTED","PROXY DATA — brand/service visibility","No paid-ad conclusion","Channel-led","CG150/200 only after mounting/output/electrical confirmation","Do not imply interchangeability","P4-PE-02,P4-PE-09","Medium"],
  ["Peru","Lifan","Lifan","CG200 long-shaft cargo engine; cargo vehicle/parts signals","200","Cargo motorcycle / trimoto","Marketplace official store","Retail-visible supply","Government/marketplace proxy","Retail complete-engine listing","NOT TESTED","PROXY DATA — SERP/listing","No paid-ad conclusion","Mixed retail/channel","CG200 cargo validation; mixed engine+parts offer","Price/compatibility unverified","P4-PE-01,P4-PE-05,P4-PE-06","Medium"],
  ["Peru","Wanxin","Wanxin","150-class trimoto model in government record; parts mentions","150","Passenger trimoto","NOT VERIFIED","NOT VERIFIED","Government model record","NOT TESTED","NOT TESTED","PROXY DATA","No paid-ad conclusion","NOT TESTED","Platform research only","No direct buyer evidence","P4-PE-01,P4-PE-04","Low"],
  ["Peru","Motorcykel catalogue","TGAP / multiple brands","CG125/150/200/250 and cargo-related parts","125–250","After-sales / repair","Importer-wholesaler claim","Wholesale parts catalogue","Catalogue breadth","Parts only","NOT TESTED","PROXY DATA — catalogue nomenclature","No paid-ad conclusion","Wholesale parts channel","Parts pack; technical confirmation service","Parts not engine demand","P4-PE-04","Medium"],
  ["Uzbekistan","Loncin","Loncin","LX250ZH-11 cargo tricycle","250","Cargo tricycle","Multiple Smart Market sellers","Marketplace vehicle offers","Repeated marketplace offers","NOT TESTED","NOT TESTED","PROXY DATA — product/listing names","Yandex Market only a marketplace signal","Marketplace fragmentation","Water-cooled cargo research; factory fit confirmation","No engine-only demand proof","P4-UZ-01,P4-UZ-02,P4-UZ-05","Medium"],
  ["Uzbekistan","Lifan","Lifan","Motorcycle engines catalogue","Unknown","Motorcycle engine / service","Bikeland","Public engine catalogue","Channel signal","Engine catalogue; model demand NOT TESTED","NOT TESTED","PROXY DATA","No paid-ad conclusion","NOT TESTED","Validate product data and buyer role","No cargo-250 proof","P4-UZ-03","Medium"],
  ["Uzbekistan","Zongshen","Zongshen","CB/CG250-related parts; used-market brand mention","250 proxy","Motorcycle/cargo-motorcycle research","NOT VERIFIED","Marketplace/parts visibility","Low-confidence proxy","Parts only","NOT TESTED","PROXY DATA","No paid-ad conclusion","NOT TESTED","Keyword research only","Parts/used listings not engine demand","P4-UZ-06,P4-UZ-07","Low"],
  ["Uzbekistan","Yandex Market ecosystem","Multiple","Loncin/Lifan motorcycle parts taxonomy","Unknown","After-sales parts","Marketplace","Marketplace","Parts taxonomy","Parts only","NOT TESTED","PROXY DATA","Yandex marketplace visibility only","NOT TESTED","Parts pack SEO/dealer research","Do not treat as Wordstat","P4-UZ-04","Low"]
];
function peKeywords() { const seeds=["motor cg150","motor cg200","motor cg250 carguero","motor para mototaxi","motor para trimoto carga","motor para motocarro","motor lifan cg200","motor zongshen 150","repuestos cg150","repuestos cg200"]; const mods=["","completo","mayorista","proveedor","distribuidor","importador"]; return seeds.flatMap(seed=>mods.map(mod=>["Peru","Spanish",[seed,mod].filter(Boolean).join(" "),"", "", "PROXY DATA",seed.includes("200")?"CG200 air-cooled":seed.includes("150")?"CG150 air-cooled":"Engine parts / spares pack",seed.includes("moto")?"mototaxi / cargo / work motorcycle":"after-sales",mod?"Commercial research":"Product research",mod?"B2B":"Unknown",mod?"Consideration":"Discovery","Unknown","PROXY DATA","","Unknown","Google","Phrase / exact after validation",seed.includes("200")?"PE | CG200 Cargo":seed.includes("150")?"PE | CG150":"PE | Parts / Replacement","/es/peru/","No","",seed.includes("lifan")||seed.includes("zongshen")?"Yes":"No",seed.includes("lifan")||seed.includes("zongshen")?"Research only; no ad-copy use":"","P4-PE-02,P4-PE-04,P4-PE-05,P4-PE-06,P4-PE-07,P4-PE-08","Medium"])); }
function uzKeywords() { const ru=["двигатель для грузового трицикла","двигатель 250 для трицикла","двигатель водяного охлаждения 250","двигатель Loncin 250","двигатель Lifan для мотоцикла","двигатель CG250","запчасти Loncin","запчасти Zongshen 250"]; const uz=["yuk tritsikli dvigateli","suv sovutgichli 250 motor"]; const ruMods=["","купить","оптом","поставщик","дистрибьютор","импортер"]; const uzMods=["","sotib olish","ulgurji","yetkazib beruvchi","distribyutor","importchi"]; const rows=(seeds,mods,lang)=>seeds.flatMap(seed=>mods.map(mod=>["Uzbekistan",lang,[seed,mod].filter(Boolean).join(" "),"","","PROXY DATA",seed.includes("250")||seed.includes("250")?"CG150–250 water-cooled cargo":"Engine parts / spares pack",seed.includes("трицикл")||seed.includes("tritsikl")?"cargo tricycle":"after-sales",mod?"Commercial research":"Product research",mod?"B2B":"Unknown",mod?"Consideration":"Discovery","Unknown","PROXY DATA","","Unknown","Google / Yandex","Phrase / exact after validation",seed.includes("запчасти")?"UZ | Parts / Dealer":"UZ | Water-Cooled Cargo","/ru/central-asia/ proposal","No","",seed.includes("Loncin")||seed.includes("Lifan")||seed.includes("Zongshen")?"Yes":"No",seed.includes("Loncin")||seed.includes("Lifan")||seed.includes("Zongshen")?"Research only; no ad-copy use":"","P4-UZ-01,P4-UZ-03,P4-UZ-04,P4-UZ-05,P4-UZ-06,P4-UZ-07","Medium"])); return [...rows(ru,ruMods,"Russian"),...rows(uz,uzMods,"Uzbek")]; }
const globalNeg = ["free","manual","pdf","jobs","salary","toy","game","wallpaper","drawing","car engine","lawn mower","used complete motorcycle","repair near me","diy","tutorial","motorcycle for sale","Bajaj","TVS","Hero","Piaggio Ape","Mahindra","Royal Enfield"];
const negativeRows = ["Peru","Uzbekistan"].flatMap(country=>globalNeg.map(term=>[country,country==="Peru"?"Spanish / English":"Russian / Uzbek / English",term,"Campaign / ad-group scoped",["Bajaj","TVS","Hero","Piaggio Ape","Mahindra","Royal Enfield"].includes(term)?"Excluded Indian platform in non-compatible ad groups":"Low-value, B2C, non-product or irrelevant intent",["Bajaj","TVS","Hero","Piaggio Ape","Mahindra","Royal Enfield"].includes(term)?"YES":"NO","P4-PE-01,P4-UZ-01","Medium"]));
const campaignRows = [
  ["Peru","Google Search","PE | CG200 Cargo","PE | CG200 Cargo Complete","CG200 air-cooled","Commercial B2B research","CG200 carguero / complete engine","PE global + Indian-platform scoped","/es/peru/ (reorder requirement)","Request technical confirmation","DESIGN ONLY","Phase 3 Ads Launch NOT APPROVED","P4-PE-05,P4-PE-06,P4-PE-08","Medium"],
  ["Peru","Google Search","PE | CG150 Trimoto","PE | CG150 Trimoto / Work","CG150 air-cooled","Commercial B2B research","CG150 / trimoto / mototaxi","PE global + Indian-platform scoped","/es/peru/ (reorder requirement)","Request technical confirmation","DESIGN ONLY","Phase 3 Ads Launch NOT APPROVED","P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-07","Medium"],
  ["Peru","Google Search","PE | Parts Pack","PE | CG Parts Wholesale","Engine parts / spares pack","Wholesale after-sales","CG125/150/200/250 parts","PE global; retain relevant repair/parts terms","/es/peru/ (parts section requirement)","Request catalogue","DESIGN ONLY","Phase 3 Ads Launch NOT APPROVED","P4-PE-04","Medium"],
  ["Uzbekistan","Google Search","UZ | Water-Cooled Cargo","UZ | 250 Cargo Tricycle","CG150–250 water-cooled cargo","Commercial research","грузовой трицикл 250 / water-cooled cargo","UZ global + Indian-platform scoped","/ru/uzbekistan/ proposal","Request vehicle/engine specification","DESIGN ONLY","Phase 3 Ads Launch NOT APPROVED","P4-UZ-01,P4-UZ-02,P4-UZ-05","Medium"],
  ["Uzbekistan","Yandex Search (design)","UZ | Cargo Engine","UZ | Russian Cargo Terms","CG150–250 water-cooled cargo","Commercial research","двигатель для грузового трицикла / 250","UZ global + Indian-platform scoped","/ru/uzbekistan/ proposal","Request technical confirmation","DESIGN ONLY","Phase 3 Ads Launch NOT APPROVED; platform/search data NOT TESTED","P4-UZ-01,P4-UZ-04,P4-UZ-05","Low"],
  ["Uzbekistan","Google / Yandex Search (design)","UZ | Parts / Dealer","UZ | Parts Wholesale","Engine parts / spares pack","Dealer / wholesale research","запчасти Loncin / Zongshen","UZ global; do not globally block valid Chinese-platform terms","/ru/uzbekistan/ proposal","Request catalogue","DESIGN ONLY","Phase 3 Ads Launch NOT APPROVED","P4-UZ-03,P4-UZ-04,P4-UZ-07","Low"]
];
const landingRows = [
  ["Peru","Spanish","Motores CG para trimoto y carga — confirme su configuración","CG200 air-cooled","CG150 air-cooled","Cargo trimoto; mototaxi; work motorcycle","CG150 vs CG200 only after specification confirmation","Complete-engine vs parts pack; do not claim fit by displacement","Use 'confirmamos eje, montaje y sistema eléctrico'; avoid competitor compatibility claims","Technical data, application, parts pack, MOQ/price only when factory-confirmed","Country; application; product; technical confirmation","Pre-filled enquiry only; do not submit","Motores CG para trimoto y carga | Chixiang","Motores y paquetes de repuestos para aplicaciones CG; confirme configuración técnica antes de comprar.","PE | CG200 Cargo; PE | CG150 Trimoto; PE | Parts Pack","P4-PE-01,P4-PE-05,P4-PE-07","Medium","NO PRODUCTION CHANGE"],
  ["Uzbekistan","Russian + Uzbek","Двигатели для грузовых трициклов — требуется техническое подтверждение","CG150–250 water-cooled cargo","Engine parts / spares pack","Cargo tricycle; dealer/parts channel","250 water-cooled cargo only after output/drive confirmation","Separate vehicle/assembly signal from replacement engine","Use 'проверим вал, крепления и электрику'; no Loncin equivalence claim","Cargo vehicle evidence; specification form; Russian/Uzbek terminology","Country; vehicle use; engine code; technical confirmation","Pre-filled enquiry only; do not submit","Двигатели для грузовых трициклов | Chixiang","Техническое подтверждение перед поставкой двигателя для грузовой техники.","UZ | Water-Cooled Cargo; UZ | Parts / Dealer","P4-UZ-01,P4-UZ-03,P4-UZ-05","Medium","NO PRODUCTION CHANGE"]
];
const budgetRows = [
  ["Model A — 2 countries","Peru","CG200/CG150 + parts",55,"Largest Batch 1 evidence breadth and Spanish existing-page audit; allocation is a ratio only","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","Ads Launch NOT APPROVED","P4-PE-01,P4-PE-04,P4-PE-05,P4-PE-07","Medium"],
  ["Model A — 2 countries","Uzbekistan","Water-cooled cargo + parts",45,"Water-cooled 250 cargo-tricycle product signal; Yandex/Google data unavailable","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","Ads Launch NOT APPROVED","P4-UZ-01,P4-UZ-02,P4-UZ-03","Medium"],
  ["Model C — product lines","Peru","CG air-cooled",45,"Demand-proxy breadth only","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","Ads Launch NOT APPROVED","P4-PE-01,P4-PE-05,P4-PE-07","Medium"],
  ["Model C — product lines","Uzbekistan","Water-cooled cargo",40,"250 water-cooled cargo-tricycle listing proxy only","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","Ads Launch NOT APPROVED","P4-UZ-01,P4-UZ-02","Medium"],
  ["Model C — product lines","Both","Parts / spares pack",15,"Parts channel signal; do not treat as complete-engine lead volume","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","Ads Launch NOT APPROVED","P4-PE-04,P4-UZ-03,P4-UZ-04","Low"]
];
await book("Phase_4_Country_Product_Demand_Ranking.xlsx","Rankings",["Country","Rank","Product","Demand score (0-100)","Opportunity tier","Demand type","Main vehicle/application","Score rationale","Evidence IDs","Confidence","Factory specification required"],[...demandRows("Peru"),...demandRows("Uzbekistan")].sort((a,b)=>a[0].localeCompare(b[0])||b[2]-a[2]).map((r,i,all)=>[r[0],1+all.filter(x=>x[0]===r[0]&&x[2]>r[2]).length,...r.slice(1)]));
await book("Phase_4_Product_Country_Matrix.xlsx","Matrix",["Country","Product","Demand score (0-100)","Opportunity tier","Demand type","Main vehicle/application","Score rationale","Evidence IDs","Confidence","Factory specification required"],[...demandRows("Peru"),...demandRows("Uzbekistan")]);
await book("Phase_4_Competitor_Product_Map.xlsx","Competitors",["Country","Brand","Local spelling","Main products","Displacement","Vehicle/application","Importer/dealer","Retail/wholesale","Parts network","Complete-engine sales","Price level","Search visibility","Google/Yandex ads visibility","Channel concentration","Chixiang opportunity","Risk","Evidence IDs","Confidence"],competitorRows);
await book("Phase_4_Keyword_Master.xlsx","Keywords",["Country","Language","Keyword","Local variation","No-accent/transliteration","Chinese meaning","Product","Vehicle/application","Intent","B2B/B2C","Funnel stage","Estimated demand level","Search-volume source","CPC/range","Competition","Google/Yandex","Recommended match type","Ad group","Landing page","Negative?","Negative reason","Competitor term?","Trademark risk","Evidence IDs","Confidence"],[...peKeywords(),...uzKeywords()]);
await book("Phase_4_Negative_Keywords.xlsx","Negatives",["Country","Language","Negative keyword","Match scope","Reason","Indian-platform exclusion","Evidence IDs","Confidence"],negativeRows);
await book("Phase_4_Campaign_Architecture.xlsx","Campaigns",["Country","Platform","Campaign","Ad group","Primary product","Intent","Keyword theme","Negative list","Landing page","CTA","Status","Gate constraint","Evidence IDs","Confidence"],campaignRows);
await book("Phase_4_Landing_Page_Roadmap.xlsx","Landing Pages",["Market","Language","Hero H1","Primary product","Secondary product","Application cards","Comparison","Replacement section","Competitor/compatibility wording","FAQ","Form defaults","WhatsApp message","SEO title","Meta description","Google/Yandex ad groups","Evidence IDs","Confidence","Production change status"],landingRows);
await book("Phase_4_Budget_Models.xlsx","Budget Models",["Model","Country","Product line","Allocation percentage","Allocation basis","CPC availability","Margin availability","Landing-page readiness","Country risk","Gate constraint","Evidence IDs","Confidence"],budgetRows);
