import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const root = fileURLToPath(new URL("../", import.meta.url));
const out = `${root}deliveries/2026-07-16_phase-4-batch-1-1-freeze/`;
const data = `${root}data/`;
const header = { fill: "#1F4E78", font: { bold: true, color: "#FFFFFF" }, wrapText: true };
const input = { fill: "#FFF2CC" };
const products = ["CG125 air-cooled","CG150 air-cooled","CG175 air-cooled","CG200 air-cooled","CG250 air-cooled","CG150-250 water-cooled cargo","Tsunami water-cooled / dual-cooled","Hanwei 200","Hanwei 250","Hanwei 300","Hanwei 350","Honda-style 110 horizontal","Honda-style 125 horizontal","Honda-style 130/140 horizontal","Lower-mounted 140","Automatic-clutch CG","Automatic-clutch horizontal","CB150/200/250 off-road","EFI water-cooled","Engine parts / spares pack"];
const col=n=>{let s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s};
const tier=n=>n>=75?"S":n>=60?"A":n>=45?"B":n>=30?"C":"D";
async function book(name,sheets){await fs.mkdir(out,{recursive:true});const wb=Workbook.create();for(const x of sheets){const ws=wb.worksheets.add(x.name), end=col(x.headers.length);ws.getRange(`A1:${end}${x.rows.length+1}`).values=[x.headers,...x.rows];ws.getRange(`A1:${end}1`).format=header;ws.getRange(`A:${end}`).format.columnWidth=18;ws.getRange(`A1:${end}${x.rows.length+1}`).format.wrapText=true;ws.getRange(`A1:${end}1`).format.rowHeight=34;ws.freezePanes.freezeRows(1);ws.showGridLines=false;if(x.formulas)for(const f of x.formulas)ws.getRange(f.range).formulas=f.values;if(x.inputs)ws.getRange(x.inputs).format=input;}const err=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:20}});if(!err.ndjson.includes("matched 0"))throw Error(`${name}: formula error`);const f=await SpreadsheetFile.exportXlsx(wb);await f.save(`${out}${name}`)}
const supported={
 Peru:{"CG150 air-cooled":[22,10,10,9,4,7,"P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-07","150-class trimoto platform, local vehicle/channel signal and complete-engine listing; fit remains model-specific.","High","Medium","Low","ENGINE-V1","trimoto / mototaxi / work motorcycle"],"CG200 air-cooled":[24,12,10,10,4,7,"P4-PE-05,P4-PE-06,P4-PE-08","CG200 complete-engine listings and cargo-engine signal; channel and interface still require validation.","High","Medium","Low","ENGINE-V1","cargo motorcycle / cargo trimoto"],"CG250 air-cooled":[9,3,3,3,2,4,"P4-PE-08","Cargo-engine signal only; research direction, not an interchangeable replacement claim.","Low","Low","Low","ENGINE-V1","NOT TESTED"],"Engine parts / spares pack":[24,0,12,8,5,8,"P4-PE-04","Wholesale catalogue covers CG125/150/200/250 parts; tracked under an aftermarket model.","High","Not applicable","Not applicable","AFTERMARKET-V1","after-sales workshop / wholesaler"]},
 Uzbekistan:{"CG150-250 water-cooled cargo":[22,3,10,9,3,6,"P4-UZ-01,P4-UZ-02,P4-UZ-05","Repeated water-cooled 250 cargo-tricycle vehicle listings; no independent engine replacement proof or fit confirmation.","Medium","Low","Low","ENGINE-V1","250 cc cargo tricycle"],"Engine parts / spares pack":[12,0,7,6,3,7,"P4-UZ-03,P4-UZ-04,P4-UZ-07","Lifan catalogue and marketplace parts taxonomy; parts-only evidence.","Medium","Not applicable","Not applicable","AFTERMARKET-V1","after-sales parts channel"]}
};
function row(country,p){const x=supported[country][p]||[0,0,0,0,0,0,"No product-specific evidence","No product-specific country evidence; unscored commercial components remain zero.","Low","Low","Low",p.includes("parts")?"AFTERMARKET-V1":"ENGINE-V1","NOT TESTED"];const [a,b,c,d,e,f,ids,why,market,demand,fit,model,vehicle]=x;const type=p.includes("parts")?"Aftermarket / parts":"Engine";return [country,p,a,b,c,d,e,f,null,null,type,vehicle,why,ids,market,demand,fit,p.includes("parts")?"PART-NUMBER-SPECIFIC":"MODEL-SPECIFIC",model,"INPUT REQUIRED",null]}
const matrix=[...products.map(p=>row("Peru",p)),...products.map(p=>row("Uzbekistan",p))];
const mf=matrix.map((r,i)=>({range:`I${i+2}:J${i+2}`,values:[[`=SUM(C${i+2}:H${i+2})`,`=IF(I${i+2}>=75,"S",IF(I${i+2}>=60,"A",IF(I${i+2}>=45,"B",IF(I${i+2}>=30,"C","D"))))`]]}));
const gf=matrix.map((r,i)=>({range:`U${i+2}`,values:[[`=IF(Q${i+2}="Low","VALIDATE FIT",IF(P${i+2}="Low","VALIDATE DEMAND",IF(T${i+2}="INPUT REQUIRED","VALIDATE ECONOMICS","READY FOR ADS REVIEW")))`]]}));
await book("Phase_4_Product_Country_Matrix_v3.xlsx",[{name:"Product Country Matrix",headers:["Country","Product","Platform / vehicle fit (0-30)","Complete-engine demand (0-20)","Competitor / channel education (0-15)","Search / advertising intent (0-15)","Competition / profit space (0-10)","Chixiang supply advantage (0-10)","Total score (formula)","Opportunity tier (formula)","Demand type","Main vehicle/application","Component rationale","Evidence IDs","Market-direction confidence","Complete-engine-demand confidence","Compatibility confidence","Compatibility requirement","Scoring model version","Economics status","Launch eligibility (formula)"],rows:matrix,formulas:[...mf,...gf]}]);
const engines=country=>matrix.filter(r=>r[0]===country&&r[10]==="Engine").map(r=>({...r,n:r.slice(2,8).reduce((a,b)=>a+b,0)})).sort((a,b)=>b.n-a.n).slice(0,3).map((r,i)=>[country,i+1,r[1],r.n,tier(r.n),r[11],r[12],r[13],r[14],r[15],r[16],r[20]]);
const aftermarket=[["Peru",1,"CG engine parts / spares pack",57,"B","Aftermarket / parts","P4-PE-04","High","Not applicable","PART-NUMBER-SPECIFIC","VALIDATE ECONOMICS"],["Peru",2,"CG200 engine + matching parts pack",45,"B","Aftermarket / parts","P4-PE-04,P4-PE-05,P4-PE-06","Medium","Low","MODEL-SPECIFIC","VALIDATE FIT"],["Uzbekistan",1,"Engine parts / spares pack",35,"C","Aftermarket / parts","P4-UZ-03,P4-UZ-04,P4-UZ-07","Medium","Not applicable","PART-NUMBER-SPECIFIC","VALIDATE ECONOMICS"],["Uzbekistan",2,"Cargo technical spares bundle",20,"D","Aftermarket / parts","P4-UZ-01,P4-UZ-05","Low","Low","MODEL-SPECIFIC","VALIDATE FIT"]];
await book("Phase_4_Country_Product_Demand_Ranking_v3.xlsx",[{name:"Engine Demand Ranking",headers:["Country","Engine rank","Product","Total score","Tier","Main vehicle/application","Component rationale","Evidence IDs","Market-direction confidence","Complete-engine-demand confidence","Compatibility confidence","Launch eligibility"],rows:[...engines("Peru"),...engines("Uzbekistan")]},{name:"Aftermarket Offer Ranking",headers:["Country","Offer rank","Aftermarket offer","Total score","Tier","Demand type","Evidence IDs","Market-direction confidence","Complete-engine-demand confidence","Compatibility requirement","Launch eligibility"],rows:aftermarket}]);
const competitors=[["Peru","Competitor brand","Zonsen / Zongshen","Zonsen","Grupo Cayman","Dealer/service channel","Unknown","Observed active","150 cc trimoto; parts/service","150","trimoto","NOT TESTED","P4-PE-02,P4-PE-09","Medium","Partial"],["Peru","Competitor brand","Lifan","Lifan","ML Peru listing publisher","Marketplace retail listing","Unknown","Observed active","CG200 long-shaft cargo engine","200","cargo motorcycle / trimoto","Yes - retail listing observed","P4-PE-05,P4-PE-06","Medium","Partial"],["Peru","Importer / distributor","Motorcykel Peru","TGAP / multiple","Motorcykel Peru","Importer/wholesaler claim","Unknown","Observed active","CG parts catalogue","125-250","after-sales","Parts only","P4-PE-04","Medium","Partial"],["Peru","Competitor brand","Loncin","Loncin","Unknown","Unknown","Unknown","Unknown","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","Low","Unknown"],["Peru","Competitor brand","Shineray","Shineray","Unknown","Unknown","Unknown","Unknown","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","Low","Unknown"],["Peru","Competitor brand","Wanhu/Wanxin","Wanxin","Unknown","Unknown","Unknown","Unknown","150-class platform record only","150","trimoto","NOT TESTED","P4-PE-01","Low","Unknown"],["Uzbekistan","Competitor brand","Loncin","Loncin","Smart Market sellers","Marketplace vehicle listing","Unknown","Observed active","LX250ZH-11 cargo tricycle","250","cargo tricycle","NOT TESTED","P4-UZ-01,P4-UZ-02","Medium","Partial"],["Uzbekistan","Marketplace/channel","Yandex Market Uzbekistan","Yandex Market","Yandex Market","Marketplace taxonomy","Unknown","Observed active","Loncin/Lifan/Zongshen parts taxonomy","Unknown","after-sales","Parts only","P4-UZ-04,P4-UZ-07","Low","No"],["Uzbekistan","Competitor brand","Lifan","Lifan","Bikeland catalog","Catalogue/channel","Unknown","Observed active","Engine catalogue","Unknown","motorcycle engine","NOT TESTED","P4-UZ-03","Medium","Partial"],["Uzbekistan","Competitor brand","Zongshen","Zongshen","Unknown","Marketplace taxonomy","Unknown","Observed active","Parts listing only","Unknown","after-sales","Parts only","P4-UZ-04,P4-UZ-07","Low","Unknown"],["Uzbekistan","Competitor brand","Shineray","Shineray","Unknown","Unknown","Unknown","Unknown","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","Low","Unknown"],["Uzbekistan","Competitor brand","Wanhu/Wanxin","Wanhu/Wanxin","Unknown","Unknown","Unknown","Unknown","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","Low","Unknown"]];
await book("Phase_4_Competitor_Product_Map_v3.xlsx",[{name:"Competitor Channel Map",headers:["Country","Record type","Entity","Local spelling","Seller/entity name","Channel type","Official status verified?","Listing status","Main products","Displacement","Vehicle/application","Complete-engine sales","Evidence IDs","Confidence","Direct competitor to Chixiang product?"],rows:competitors}]);
const pe=[['motor cg 150 completo','CG150 air-cooled','trimoto / mototaxi','Complete-engine','PE | CG150 Air-Cooled Trimoto','Motor CG150 completo','/es/','/es/peru/motor-cg150-trimoto/','P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-07'],['motor cg 200 completo','CG200 air-cooled','cargo / work','Complete-engine','PE | CG200 Air-Cooled Work/Cargo','CG200 cargo engine','/es/','/es/peru/motor-cg200-carga/','P4-PE-05,P4-PE-06,P4-PE-08'],['motor cg 250 carguero','CG250 air-cooled - research only','cargo','Research only','PE | CG250 Research Only','CG250 cargo engine','/es/','/es/peru/motor-cg250-investigacion/','P4-PE-08'],['motor para trimoto de carga','CG150 air-cooled','cargo trimoto','Complete-engine','PE | CG150 Air-Cooled Trimoto','cargo trimoto engine','/es/','/es/peru/motor-cg150-trimoto/','P4-PE-01,P4-PE-03,P4-PE-07'],['motor para motocarro de carga','CG200 air-cooled','cargo motocarro','Complete-engine','PE | CG200 Air-Cooled Work/Cargo','cargo motocarro engine','/es/','/es/peru/motor-cg200-carga/','P4-PE-05,P4-PE-06'],['proveedor de motores CG','CG200 air-cooled','work/cargo','B2B supplier','PE | CG200 Air-Cooled Work/Cargo','CG engine supplier','/es/','/es/peru/motor-cg200-carga/','P4-PE-05,P4-PE-06,P4-PE-08'],['repuestos para motor CG150','Engine parts / spares pack','after-sales','Parts','PE | CG Parts','CG150 engine parts','/es/','/es/peru/repuestos-motor-cg/','P4-PE-04'],['kit de repuestos para motor CG200','Engine parts / spares pack','after-sales','Parts','PE | CG Parts','CG200 engine parts kit','/es/','/es/peru/repuestos-motor-cg/','P4-PE-04'],['motor Lifan CG 200 carguero','CG200 air-cooled','cargo','Competitor brand research','PE | CG200 Air-Cooled Work/Cargo','Lifan CG200 cargo engine','/es/','/es/peru/motor-cg200-carga/','P4-PE-05,P4-PE-06']];
const uz=[['двигатель для грузового трицикла','CG150-250 water-cooled cargo','cargo tricycle','Complete-engine research','UZ | Water-Cooled Cargo Research','cargo tricycle engine','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-01,P4-UZ-02,P4-UZ-05'],['двигатель 250 кубов для трицикла','CG150-250 water-cooled cargo','250 cargo tricycle','Complete-engine research','UZ | Water-Cooled Cargo Research','250cc tricycle engine','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-01,P4-UZ-02'],['двигатель 250 см3 с водяным охлаждением','CG150-250 water-cooled cargo','water-cooled cargo','Complete-engine research','UZ | Water-Cooled Cargo Research','250cc water-cooled engine','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-01,P4-UZ-05'],['двигатели для трициклов оптом','CG150-250 water-cooled cargo','cargo tricycle','Wholesale research','UZ | Water-Cooled Cargo Research','wholesale tricycle engines','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-01,P4-UZ-02'],['поставщик двигателей для мототехники','CG150-250 water-cooled cargo','motorcycle equipment','B2B supplier','UZ | Water-Cooled Cargo Research','motorcycle engine supplier','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-03,P4-UZ-05'],['запчасти для двигателя Loncin','Engine parts / spares pack','after-sales','Parts','UZ | Parts / Dealer','Loncin engine parts','/ru/central-asia/','/ru/uzbekistan/zapchasti-dvigatelya/','P4-UZ-04,P4-UZ-07'],['запчасти Zongshen 250','Engine parts / spares pack','after-sales','Parts','UZ | Parts / Dealer','Zongshen 250 parts','/ru/central-asia/','/ru/uzbekistan/zapchasti-dvigatelya/','P4-UZ-04,P4-UZ-07'],['двигатель Lifan для мотоцикла','CG150-250 water-cooled cargo','motorcycle','Competitor brand research','UZ | Water-Cooled Cargo Research','Lifan motorcycle engine','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-03'],['yuk tritsikli dvigateli','CG150-250 water-cooled cargo','cargo tricycle','Research only','UZ | Water-Cooled Cargo Research','cargo tricycle engine','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','P4-UZ-01']];
function kw(country,language,rows){return rows.map((r,i)=>[country,language,r[0],r[5],r[1],r[2],r[3],r[4],r[6],r[7],"qualification form","PROPOSAL - DO NOT BUILD","Retained",r[3].includes("Parts")?"FIT REVIEW REQUIRED":"NATIVE REVIEW REQUIRED",language==="Spanish"?"Observed in local source":"Machine-generated - review required",i<3?"High":i<6?"Medium":"Low","PROXY DATA","Local-source/marketplace terminology; no volume or CPC asserted.","2026-07-16",r[8],r[0].toLowerCase().includes("lifan")?"Competitor brand keyword; trademark review required; do not use in ad copy":"Generic / research term"])}
const keywords=[...kw("Peru","Spanish",pe),...kw("Uzbekistan","Russian",uz)];
await book("Phase_4_Keyword_Master_v3.xlsx",[{name:"Keyword Master",headers:["Country","Language","Keyword","Chinese meaning","Product","Vehicle/application","Intent","Ad group","Current landing URL","Proposed landing URL","Page module/section","Implementation status","Research status","Ads eligibility","Native wording status","Estimated demand level","Search-volume source","Proxy rationale","Access date","Evidence IDs","Brand-term control"],rows:keywords}]);
const negatives=[["Peru","Spanish","gratis","Negative phrase","Google Ads","Campaign","Free intent","Policy / strategy rule"],["Peru","Spanish","empleo","Negative phrase","Google Ads","Campaign","Jobs intent","Policy / strategy rule"],["Peru","Spanish","moto usada","Negative phrase","Google Ads","Campaign","Used vehicle intent","Policy / strategy rule"],["Peru","Spanish","manual pdf","Negative phrase","Google Ads","Campaign","Manual intent","Policy / strategy rule"],["Peru","Spanish","Bajaj","Negative phrase","Google Ads","Ad group","Excluded Indian platform; confirm fit first","Policy / strategy rule"],["Uzbekistan","Russian","бесплатно","Negative phrase","Yandex / Google research","Campaign","Free intent","Policy / strategy rule"],["Uzbekistan","Russian","работа","Negative phrase","Yandex / Google research","Campaign","Jobs intent","Policy / strategy rule"],["Uzbekistan","Russian","мотоцикл б/у","Negative phrase","Yandex / Google research","Campaign","Used vehicle intent","Policy / strategy rule"],["Uzbekistan","Russian","инструкция pdf","Negative phrase","Yandex / Google research","Campaign","Manual intent","Policy / strategy rule"],["Uzbekistan","Russian","Bajaj","Negative phrase","Yandex / Google research","Ad group","Excluded Indian platform; confirm fit first","Policy / strategy rule"]];
await book("Phase_4_Negative_Keywords_v3.xlsx",[{name:"Negative Keywords",headers:["Country","Language","Negative keyword","Match type","Platform","Level","Reason","Evidence IDs / rule"],rows:negatives}]);
const dict=await fs.readFile(`${data}phase4_batch11_data_dictionary.csv`,"utf8");const drows=dict.trim().split("\n").slice(1).map(x=>x.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/));
await book("Phase_4_Data_Dictionary_v1.xlsx",[{name:"Data Dictionary",headers:["Domain","Allowed value","Definition"],rows:drows}]);
const factory=[['Peru CG200 air-cooled cargo/long-shaft candidate','INPUT REQUIRED'],['Peru CG150 air-cooled trimoto candidate','INPUT REQUIRED'],['Uzbekistan 250-class water-cooled cargo candidate','INPUT REQUIRED']];const fields=['Factory model code','Engine family/code','Actual displacement','Cooling system','Bore x stroke','Rated/max power and RPM','Torque and RPM','Gearbox and gear pattern','Clutch type','Starter type','Ignition/CDI/ECU type','Charging output','Carburetor/EFI','Output shaft length/diameter/spline','Final-drive type','Mount drawing/dimensions','Overall dimensions','Net/gross weight','Included accessories','Packing dimensions','MOQ','Certificates','Warranty terms','Current export markets'];
await book("Phase_4_Factory_Spec_Master_v1.xlsx",[{name:"Factory Spec Master",headers:["Required field",...factory.map(x=>x[0])],rows:fields.map(f=>[f,...factory.map(()=>"INPUT REQUIRED")]),inputs:"B2:D25"}]);
const check=['Current engine brand/model code','Vehicle make/model/year','Engine and mount photos','Output shaft measurements','Electrical connector photos','Required quantity','Destination city/port','Replacement or new-assembly use','Factory model candidate','Reviewer decision'];
await book("Phase_4_Compatibility_Checklist_v1.xlsx",[{name:"Compatibility Checklist",headers:["Field","Peru CG200","Peru CG150","Uzbekistan water-cooled cargo","Control"],rows:check.map(f=>[f,'INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','Do not claim compatibility before interface review'])}]);
const termrows=[...pe.slice(0,5).map(x=>['Peru','Spanish',x[0],x[5],'Machine-generated - review required','INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','Phrase','No named reviewer']),...uz.slice(0,5).map(x=>['Uzbekistan','Russian',x[0],x[5],'Machine-generated - review required','INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','Phrase','No named reviewer'])];
await book("Phase_4_Native_Term_Review_v1.xlsx",[{name:"Native Term Review",headers:["Country","Language","Original term","Chinese meaning","Review status","Reviewer","Review date","Naturalness score","Recommended match type","Notes"],rows:termrows,inputs:"F2:H11"}]);
await book("Phase_4_Search_Data_Validation_v1.xlsx",[{name:"Search Data Validation",headers:["Country","Language","Keyword","Platform","Monthly searches / forecast","Competition","CPC/bid forecast","Date range","Source screenshot/export","Status"],rows:keywords.map(k=>[k[0],k[1],k[2],k[0]==='Peru'?'Google Keyword Planner':'Google/Yandex Wordstat','', '','', '','INPUT REQUIRED','NOT TESTED']),inputs:"E2:I19"}]);
const buyers=[['Peru','INPUT REQUIRED','Importer / assembler / dealer / workshop','INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','Unknown','INPUT REQUIRED','CONTACT NOT APPROVED'],['Uzbekistan','INPUT REQUIRED','Cargo-tricycle dealer / engine distributor / workshop','INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','Unknown','INPUT REQUIRED','CONTACT NOT APPROVED']];
await book("Phase_4_Buyer_Channel_Candidate_List_v1.xlsx",[{name:"Buyer Channel Candidates",headers:["Country","Legal entity / website","Role","City","Products observed","Complete-engine evidence","Contact channel","Proposed validation question","Contact approval status"],rows:buyers,inputs:"B2:H3"}]);
const economics=['EXW/FOB price by quantity tier','MOQ','Tooling/customization cost','Packaging','Spare-parts bundle cost','Warranty reserve','Lead time','Payment terms','Carton/crate dimensions and weight','Freight quotation date','Origin/destination','Insurance','Customs code candidate','Duty/VAT/taxes','Local delivery/broker costs'];
await book("Phase_4_Economics_Input_Register_v1.xlsx",[{name:"Economics Input Register",headers:["Input","Peru CG200","Peru CG150","Uzbekistan water-cooled cargo","Source / date","Status"],rows:economics.map(x=>[x,'INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED','INPUT REQUIRED']),inputs:"B2:F16"}]);
await book("Phase_4_Landing_Page_Roadmap_v2.xlsx",[{name:"Landing Page Roadmap",headers:["Country","Current URL","Proposed URL","Page module/section","Implementation status","Product scope","Prohibited claims","Language review status","Implementation gate"],rows:[['Peru','/es/','/es/peru/motor-cg200-carga/','engine application + specification qualification form','DESIGN ONLY','CG200 air-cooled cargo/work','Do not claim compatibility by displacement','Spanish source review required','NOT APPROVED'],['Peru','/es/','/es/peru/motor-cg150-trimoto/','trimoto application + specification qualification form','DESIGN ONLY','CG150 air-cooled trimoto','Do not claim compatibility by displacement','Spanish source review required','NOT APPROVED'],['Peru','/es/','/es/peru/repuestos-motor-cg/','parts identification + application form','DESIGN ONLY','CG parts pack','Do not imply complete engine demand','Spanish source review required','NOT APPROVED'],['Uzbekistan','/ru/central-asia/','/ru/uzbekistan/gruzovoy-tritsikl-dvigatel/','research wireframe + technical qualification form','DESIGN ONLY','250-class water-cooled cargo research','Do not claim direct replacement or compatibility','Russian native review required','NOT APPROVED']]}]);
const evidence=[['P4V-PE-01','Peru','CG150 air-cooled','Derived audit control','Keyword/product mapping reviewed against existing product-scoped v2 evidence','P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-07','2026-07-16','Internal audit record','No new market fact','Keyword mapping / scoring'],['P4V-PE-02','Peru','CG200 air-cooled','Derived audit control','Keyword/product mapping reviewed against CG200 listing evidence','P4-PE-05,P4-PE-06,P4-PE-08','2026-07-16','Internal audit record','No new market fact','Keyword mapping / scoring'],['P4V-UZ-01','Uzbekistan','CG150-250 water-cooled cargo','Derived audit control','Vehicle signal retained separately from complete-engine demand and fit','P4-UZ-01,P4-UZ-02,P4-UZ-05','2026-07-16','Internal audit record','No new market fact','Demand/fit gate']];
const csv=v=>`"${String(v).replaceAll('"','""')}"`;
const csvrow=a=>a.map(csv).join(',');
const gate=r=>r[16]==='Low'?'VALIDATE FIT':r[15]==='Low'?'VALIDATE DEMAND':'VALIDATE ECONOMICS';
await fs.writeFile(`${data}phase4_batch11_product_matrix.csv`,[csvrow(['Country','Product','Platform','Engine demand','Channel','Search','Profit','Supply','Total','Tier','Demand type','Evidence IDs','Market confidence','Engine confidence','Compatibility confidence','Launch eligibility']),...matrix.map(r=>{const total=r.slice(2,8).reduce((a,b)=>a+b,0);return csvrow([r[0],r[1],...r.slice(2,8),total,tier(total),r[10],r[13],r[14],r[15],r[16],gate(r)])})].join('\n'));
await fs.writeFile(`${data}phase4_batch11_keywords.csv`,[csvrow(['Country','Language','Keyword','Chinese meaning','Product','Intent','Ad group','Proposed landing URL','Research status','Ads eligibility','Native wording status','Estimated demand level','Evidence IDs']),...keywords.map(r=>csvrow([r[0],r[1],r[2],r[3],r[4],r[6],r[7],r[9],r[12],r[13],r[14],r[15],r[19]]))].join('\n'));
await fs.writeFile(`${data}phase4_batch11_competitors.csv`,[csvrow(['Country','Record type','Entity','Complete-engine sales','Evidence IDs']),...competitors.map(r=>csvrow([r[0],r[1],r[2],r[11],r[12]]))].join('\n'));
await fs.writeFile(`${data}phase4_batch11_evidence_log.csv`,[csvrow(['Evidence ID','Country','Product scope','Classification','Claim','Parent evidence','Access date','Reviewer','Limitations','Supports score component(s)']),...evidence.map(csvrow)].join('\n'));
console.log(`Built Batch 1.1 outputs in ${out}`);
