import fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const phaseRoot = fileURLToPath(new URL("../", import.meta.url));
const out = `${phaseRoot}deliveries/2026-07-16_phase-4-batch-1-corrected/`;
const header = { fill: "#1F4E78", font: { bold: true, color: "#FFFFFF" }, wrapText: true };
const products = ["CG125 air-cooled","CG150 air-cooled","CG175 air-cooled","CG200 air-cooled","CG250 air-cooled","CG150–250 water-cooled cargo","Tsunami water-cooled / dual-cooled","Hanwei 200","Hanwei 250","Hanwei 300","Hanwei 350","Honda-style 110 horizontal","Honda-style 125 horizontal","Honda-style 130/140 horizontal","Lower-mounted 140","Automatic-clutch CG","Automatic-clutch horizontal","CB150/200/250 off-road","EFI water-cooled","Engine parts / spares pack"];
function col(n){let s="";while(n){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
function tier(score){return score>=75?"S":score>=60?"A":score>=45?"B":score>=30?"C":"D"}
async function exportBook(name, sheets){await fs.mkdir(out,{recursive:true});for(const spec of sheets){const bad=spec.rows.findIndex(row=>row.length!==spec.headers.length);if(bad>=0)throw new Error(`${name}/${spec.name}: row ${bad+2} has ${spec.rows[bad].length} values; expected ${spec.headers.length}`)}const wb=Workbook.create();for(const spec of sheets){const ws=wb.worksheets.add(spec.name);const last=col(spec.headers.length);ws.getRange(`A1:${last}${spec.rows.length+1}`).values=[spec.headers,...spec.rows];ws.getRange(`A1:${last}1`).format=header;ws.getRange(`A:${last}`).format.columnWidth=18;ws.getRange(`A1:${last}${spec.rows.length+1}`).format.wrapText=true;ws.getRange(`A1:${last}1`).format.rowHeight=32;ws.freezePanes.freezeRows(1);ws.showGridLines=false;if(spec.formulas){for(const {range,values} of spec.formulas)ws.getRange(range).formulas=values}}const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100}});if(!errors.ndjson.includes("matched 0"))throw new Error(`Formula error in ${name}`);const file=await SpreadsheetFile.exportXlsx(wb);await file.save(`${out}${name}`)}
const profile={
 Peru:{
  "CG125 air-cooled":[6,0,4,3,1,3,"P4-PE-04","No product-specific complete-engine evidence; parts-only channel signal.","Low","Low","Low"],
  "CG150 air-cooled":[22,10,10,9,4,7,"P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-07","150-class trimoto platform, vehicle listings and CG150 complete-engine listing; fit remains model-specific.","High","Medium","Low"],
  "CG200 air-cooled":[24,12,10,10,4,7,"P4-PE-05,P4-PE-06,P4-PE-08","Two CG200 complete-engine listings and cargo-engine search visibility; channel/fit not verified.","High","Medium","Low"],
  "CG250 air-cooled":[9,3,3,3,2,4,"P4-PE-08","Cargo-engine search result only; no product-specific wholesale or fit evidence.","Low","Low","Low"],
  "Engine parts / spares pack":[24,0,12,8,5,8,"P4-PE-04","Wholesaler catalogue covers CG125/150/200/250 engine parts in pack quantities; parts are separated from engine ranking.","High","Not applicable","Compatibility by part number"]
 },
 Uzbekistan:{
  "CG150–250 water-cooled cargo":[22,3,10,9,3,6,"P4-UZ-01,P4-UZ-02,P4-UZ-05","Repeated 250 cc water-cooled cargo-tricycle listings; vehicle signal only, not engine-only demand or Chixiang fit.","Medium","Low","Low"],
  "CG250 air-cooled":[4,0,2,2,2,4,"No product-specific evidence","No product-specific complete-engine evidence. Kept as low-confidence research direction only.","Low","Low","Low"],
  "CG200 air-cooled":[3,0,1,1,2,4,"No product-specific evidence","No product-specific country evidence. Research-only direction.","Low","Low","Low"],
  "Hanwei 250":[2,0,0,1,2,4,"No product-specific evidence","No product-specific country evidence. Research-only direction.","Low","Low","Low"],
  "Engine parts / spares pack":[12,0,7,6,3,7,"P4-UZ-03,P4-UZ-04,P4-UZ-07","Lifan engine catalogue and Loncin/Zongshen parts visibility; parts-only channel evidence.","Medium","Not applicable","Compatibility by part number"]
 }};
function matrixRows(country){return products.map(p=>{const x=profile[country][p]||[0,0,0,0,1,3,"No product-specific evidence","No product-specific country evidence; conservative score.","Low","Low","Low"];const [platform,engine,channel,search,profit,supply,evidence,rationale,market,complete,compat]=x;const type=p.includes("parts")?"Aftermarket / parts":"Engine";const vehicle=country==="Peru"?(p==="CG150 air-cooled"?"trimoto / mototaxi / work motorcycle":p==="CG200 air-cooled"?"cargo motorcycle / cargo trimoto":p.includes("parts")?"after-sales workshop / wholesaler":"NOT TESTED"):(p.includes("water-cooled cargo")?"250 cc cargo tricycle":p.includes("parts")?"after-sales parts channel":"NOT TESTED");return [country,p,platform,engine,channel,search,profit,supply,null,null,type,vehicle,rationale,evidence,market,complete,compat,p.includes("water")||p.includes("Hanwei")||p.includes("EFI")?"YES":"MODEL-SPECIFIC"]})}
const matrix=[...matrixRows("Peru"),...matrixRows("Uzbekistan")];
const formulas=matrix.map((_,i)=>({range:`I${i+2}:J${i+2}`,values:[[`=SUM(C${i+2}:H${i+2})`,`=IF(I${i+2}>=75,"S",IF(I${i+2}>=60,"A",IF(I${i+2}>=45,"B",IF(I${i+2}>=30,"C","D"))))`]]}));
const engineRank=country=>matrix.filter(r=>r[0]===country&&r[10]==="Engine").map(r=>({...r,total:r.slice(2,8).reduce((a,b)=>a+b,0)})).sort((a,b)=>b.total-a.total).slice(0,3).map((r,i)=>[country,i+1,r[1],r.total,tier(r.total),r[11],r[12],r[13],r[14],r[15],r[16]]);
const aftermarket=[
 ["Peru",1,"CG engine parts / spares pack",57,"A","Wholesale parts packs for CG125/150/200/250","P4-PE-04","High","Not applicable","Part number and application confirmation required"],
 ["Peru",2,"CG200 engine + matching parts pack",45,"B","Combination offer only after engine code/output confirmation","P4-PE-04,P4-PE-05,P4-PE-06","Medium","Low","No implied fit by displacement"],
 ["Uzbekistan",1,"Engine parts / spares pack",35,"C","Lifan/Loncin/Zongshen parts terminology and catalogue/channel signal","P4-UZ-03,P4-UZ-04,P4-UZ-07","Medium","Not applicable","Part number and application confirmation required"],
 ["Uzbekistan",2,"Cargo technical spares bundle",20,"D","Research-only bundle for 250 cargo-tricycle enquiry confirmation","P4-UZ-01,P4-UZ-05","Low","Low","No vehicle/engine interchangeability claim"]
 ];
await exportBook("Phase_4_Product_Country_Matrix_v2.xlsx",[{name:"Matrix",headers:["Country","Product","Platform / vehicle fit (0-30)","Complete-engine demand (0-20)","Competitor / channel education (0-15)","Search / advertising intent (0-15)","Competition / profit space (0-10)","Chixiang supply advantage (0-10)","Total score (formula)","Opportunity tier (formula)","Demand type","Main vehicle/application","Component rationale","Evidence IDs","Market-direction confidence","Complete-engine-demand confidence","Compatibility confidence","Factory specification required"],rows:matrix,formulas}]);
await exportBook("Phase_4_Country_Product_Demand_Ranking_v2.xlsx",[{name:"Engine Demand Ranking",headers:["Country","Engine rank","Product","Total score","Tier","Main vehicle/application","Component rationale","Evidence IDs","Market-direction confidence","Complete-engine-demand confidence","Compatibility confidence"],rows:[...engineRank("Peru"),...engineRank("Uzbekistan")]},{name:"Aftermarket Offers",headers:["Country","Offer rank","Aftermarket offer","Total score","Tier","Demand type","Evidence IDs","Market-direction confidence","Complete-engine-demand confidence","Compatibility requirement"],rows:aftermarket}]);
const competitor=[
 ["Peru","Competitor brand","Zonsen / Zongshen","Zonsen","150 cc trimoto; motorcycles; service/parts","150","Passenger/cargo trimoto","Grupo Cayman","Brand service/parts network","NOT TESTED","P4-PE-02,P4-PE-09","Medium"],
 ["Peru","Competitor brand","Lifan","Lifan","CG200 long-shaft cargo engine","200","Cargo motorcycle / trimoto","Official marketplace store","Retail complete-engine listing","P4-PE-05,P4-PE-06","P4-PE-05,P4-PE-06","Medium"],
 ["Peru","Competitor brand","Loncin","Loncin","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","No verified country-specific evidence","No verified country-specific evidence","Low"],
 ["Peru","Competitor brand","Shineray","Shineray","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","No verified country-specific evidence","No verified country-specific evidence","Low"],
 ["Peru","Competitor brand","Wanxin","Wanxin","150-class trimoto platform record","150","Passenger trimoto","No verified country-specific importer","Parts mention only","NOT TESTED","P4-PE-01","Low"],
 ["Peru","Importer/dealer","Motorcykel Peru","TGAP / multiple","CG125/150/200/250 parts","125–250","After-sales","Importer/wholesaler claim","Wholesale parts catalogue","Parts only","P4-PE-04","Medium"],
 ["Uzbekistan","Competitor brand","Loncin","Loncin","LX250ZH-11 cargo tricycle","250","Cargo tricycle","Multiple marketplace sellers","Vehicle listing; parts taxonomy","NOT TESTED","P4-UZ-01,P4-UZ-02,P4-UZ-05","Medium"],
 ["Uzbekistan","Competitor brand","Lifan","Lifan","Motorcycle engines catalogue","Unknown","Motorcycle engine/service","Bikeland","Engine catalogue","NOT TESTED","P4-UZ-03","Medium"],
 ["Uzbekistan","Competitor brand","Zongshen","Zongshen","CB/CG250 related parts and marketplace term","250 proxy","Motorcycle/cargo research","No verified importer","Parts only","NOT TESTED","P4-UZ-06,P4-UZ-07","Low"],
 ["Uzbekistan","Competitor brand","Shineray","Shineray","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","No verified country-specific evidence","No verified country-specific evidence","Low"],
 ["Uzbekistan","Competitor brand","Wanhu/Wanxin","Wanhu/Wanxin","No verified country-specific evidence","Unknown","Unknown","NOT TESTED","No verified country-specific evidence","No verified country-specific evidence","No verified country-specific evidence","Low"],
 ["Uzbekistan","Marketplace/channel","Smart Market Uzbekistan","Smart Market","Loncin vehicle listings","250","Cargo tricycle","Marketplace","Marketplace only","NOT TESTED","P4-UZ-01,P4-UZ-02,P4-UZ-05","Low"],
 ["Uzbekistan","Marketplace/channel","Yandex Market Uzbekistan","Yandex Market","Loncin/Lifan/Zongshen parts taxonomy","Unknown","After-sales","Marketplace","Parts taxonomy only","Parts only","P4-UZ-04,P4-UZ-07","Low"]
 ];
await exportBook("Phase_4_Competitor_Product_Map_v2.xlsx",[{name:"Competitor Map",headers:["Country","Record type","Entity","Local spelling","Main products","Displacement","Vehicle/application","Importer/dealer","Parts/network signal","Complete-engine sales","Evidence IDs","Confidence"],rows:competitor}]);
const peRetained=[
 "motor CG 150 completo","motor CG 200 completo","motor CG 250 carguero","motor para trimoto de carga","motor para motocarro de carga","motor para mototaxi","motores para mototaxi al por mayor","proveedor de motores CG","distribuidor de motores para trimotos","motor CG 150 para trimoto","motor CG 200 para carga","motor CG 200 eje largo","motor Lifan CG 200 carguero","motor CG 150 con eje largo","motor para moto carguera","motor de repuesto CG 150","motor de reemplazo CG 200","motor de motocicleta CG 200","motor para carga de tres ruedas","motor para tricimoto de carga","motor para moto lineal CG 150","motor CG 150 al por mayor","motor CG 200 al por mayor","importador de motores para moto","venta mayorista de motores para moto","motores para motocicleta por mayor","motor completo para motocarro","motor completo para trimoto","motor para trabajo pesado moto","motor CG para carga","repuestos para motor CG150","repuestos para motor CG200","kit de repuestos para motor CG200","kit de reparación motor CG150","kit de reparación motor CG200","repuestos de motor para trimoto","repuestos de motor para mototaxi","cigüeñal CG200","cilindro CG150","cilindro CG200","caja de cambios CG200 carguero","embrague CG250 carguero","carburador CG200","motor de arranque CG150","kit de empaques CG150","kit de empaques CG200","repuestos CG150 al por mayor","repuestos CG200 al por mayor","proveedor de repuestos para moto","distribuidor de repuestos CG","repuestos para motocarro","repuestos para trimoto","motor Zongshen 150 trimoto","motor Lifan CG200","motor CG200 Perú","motor CG150 Perú","motor para trimoto Perú","motor para mototaxi Perú","motores para carga Perú","repuestos CG Perú"];
const uzRetained=[
 "двигатель для грузового трицикла","двигатель 250 кубов для трицикла","двигатель 250 см3 с водяным охлаждением","двигатель с водяным охлаждением для трицикла","двигатели для трициклов оптом","поставщик двигателей для мототехники","двигатель для грузового мотоцикла","двигатель для грузового мотороллера","двигатель Loncin 250","двигатель Lifan для мотоцикла","двигатель CG250","двигатель для мотоцикла 250 кубов","двигатель для мототехники оптом","купить двигатель для трицикла","двигатель для трицикла купить","запчасти для двигателя Loncin","запчасти для двигателя Lifan","запчасти Zongshen 250","запчасти для грузового трицикла","запчасти для мототехники оптом","комплект запчастей для двигателя","карбюратор Zongshen 250","карбюратор CG250","запчасти для двигателя 250 кубов","запчасти для мотоцикла Loncin","запчасти для мотоцикла Lifan","поставщик запчастей для мототехники","дистрибьютор запчастей для мотоциклов","двигатель для мотоцикла Узбекистан","двигатель для трицикла Узбекистан","грузовой трицикл 250","трехколесный грузовой мотоцикл","водяное охлаждение двигатель 250","двигатель 250 для грузовой техники","двигатель для сельскохозяйственного трицикла","двигатель для хозяйственного трицикла","запчасти для трицикла 250","комплект для ремонта двигателя","ремонтный комплект CG250","двигатель Zongshen 250","двигатель Loncin для трицикла","двигатель Lifan 250","двигатель для грузового транспорта малой мощности","двигатель для мототехники купить","двигатель для мотоцикла оптом","поставщик двигателей 250 кубов","двигатель с жидкостным охлаждением","двигатель для трёхколёсного мотоцикла","запчасти для двигателя мотоцикла","запчасти Loncin купить","запчасти Lifan купить","двигатель для доставки грузов","двигатель для малого грузового транспорта","грузовой мотороллер 250","трехколесный мотоцикл двигатель","двигатель 250 для хозяйства","запчасти для грузового мотоцикла","двигатель для мотоцикла поставщик","мото двигатель 250"];
function chinese(k,country){if(country==="Peru"){if(k.includes("repuestos")||k.includes("kit")||k.includes("cigüeñal")||k.includes("cilindro")||k.includes("carburador")||k.includes("embrague")||k.includes("caja"))return "CG 发动机零件/维修件";if(k.includes("CG 200")||k.includes("CG200"))return "CG200 发动机或货运应用";if(k.includes("CG 150")||k.includes("CG150"))return "CG150 发动机或三轮车应用";return "摩托车/三轮车发动机"}if(k.includes("запчаст")||k.includes("карбюратор")||k.includes("комплект"))return "摩托车发动机零件或维修套件";if(k.includes("трицикл")||k.includes("грузов"))return "货运三轮车发动机或车辆";if(k.includes("250"))return "250cc 摩托车发动机";return "摩托车发动机"}
function classify(k,country){const parts=country==="Peru"?/repuestos|kit|cigüeñal|cilindro|carburador|embrague|caja de cambios/i:/запчаст|карбюратор|комплект/i;const isParts=parts.test(k);const product=isParts?"Engine parts / spares pack":country==="Peru"?(k.match(/CG ?150|mototaxi|trimoto/i)?"CG150 air-cooled":"CG200 air-cooled"):(/трицикл|грузов|водян|жидкост/i.test(k)?"CG150–250 water-cooled cargo":"CG250 air-cooled");const app=isParts?"after-sales / workshop":country==="Peru"?(product==="CG150 air-cooled"?"trimoto / mototaxi / work motorcycle":"cargo motorcycle / cargo trimoto"):product.includes("water")?"cargo tricycle":"motorcycle";return {isParts,product,app}}
function demandLevel(k,country){const c=classify(k,country);if(c.isParts)return "Medium";if(country==="Peru"&&/cg ?200|carguero|trimoto|mototaxi|motocarro/i.test(k))return "High";if(country==="Uzbekistan"&&/трицикл|грузов|водян|жидкост/i.test(k))return "Medium";return "Low"}
function keywordRows(country,list,evidence){const lang=country==="Peru"?"Spanish":"Russian";return list.map(k=>{const c=classify(k,country);const level=demandLevel(k,country);const campaign=country==="Peru"?(c.isParts?"PE | Parts Pack":c.product==="CG150 air-cooled"?"PE | CG150 Air-Cooled Trimoto":"PE | CG200 Air-Cooled Work/Cargo"):(c.isParts?"UZ | Parts / Dealer":c.product.includes("water")?"UZ | Water-Cooled Cargo":"UZ | CG250 SEO / Phase 2");return [country,lang,k,chinese(k,country),"Retained","Native wording verified",c.product,c.app,c.isParts?"After-sales / wholesale":"Commercial engine research",c.isParts?"B2B / mixed":"B2B research",level,"PROXY DATA",level==="High"?"Repeated product/listing + platform evidence":level==="Medium"?"Relevant listing/catalogue/terminology evidence":"Relevant terminology; weak product-specific evidence","",level==="High"?"Medium":level==="Medium"?"Medium":"Low",country==="Peru"?"Google":"Google / Yandex",campaign,c.isParts?"/es/peru/ parts section":"/es/peru/ engine section",country==="Uzbekistan"?"/ru/uzbekistan/ proposal":"/es/peru/ reorder proposal","No",c.isParts?"":"",evidence,c.isParts?"Medium":"Low"]})}
const peRejected=["motor para mototaxi mayorista","motor para trimoto carga proveedor","motor cg150 importador","motor cg200 distribuidor","repuestos cg150 completo","repuestos cg200 importador","motor para motocarro mayorista","motor zongshen 150 proveedor","motor lifan cg200 distribuidor","motor cg250 carguero importador","motor para trimoto carga completo","motor para mototaxi distribuidor","motor cg150 proveedor","motor cg200 proveedor","repuestos para motor CG150 mayorista","repuestos para motor CG200 proveedor","motor para carga importador","motor CG150 mototaxi mayorista","motor CG200 trimoto proveedor","motor para moto carguera distribuidor","motor CG250 mayorista","motor CG150 completo importador","motor CG200 completo proveedor","motor para tricimoto distribuidor","motor CG200 al por mayor proveedor","motor CG150 al por mayor proveedor","repuestos CG importador","repuestos trimoto mayorista","kit motor CG proveedor","motor para mototaxi importador","motor para carga mayorista","motor de moto proveedor Perú","motor para tres ruedas proveedor","motor CG200 proveedor Perú","motor CG150 proveedor Perú","motor trimoto importador Perú","motor mototaxi importador Perú","motor CG mayorista Perú","repuestos CG proveedor Perú","motor carguero proveedor Perú"];
const uzRejected=["двигатель для трицикла дистрибьютор","двигатель 250 для трицикла поставщик","двигатель Loncin 250 импортёр","двигатель Lifan для мотоцикла оптом купить","двигатель водяного охлаждения 250 дистрибьютор","запчасти Zongshen 250 поставщик купить","двигатель для грузового трицикла импортёр","двигатель CG250 дистрибьютор","запчасти Loncin оптом купить","двигатель для мототехники поставщик купить","двигатель 250 кубов импортёр","запчасти для трицикла поставщик купить","двигатель для трицикла оптом купить","двигатель грузовой мотоцикл дистрибьютор","двигатель Lifan 250 импортёр","двигатель Zongshen 250 поставщик","запчасти для двигателя Loncin поставщик","двигатель для мотоцикла оптом купить","двигатель для трицикла Узбекистан поставщик","двигатель для груза 250 импортёр","yuk tritsikli dvigateli","suv sovutgichli 250 motor","tritsikl motor ulgurji","Loncin 250 motor yetkazib beruvchi","Lifan motor importchi","moto dvigatel 250 ulgurji","Zongshen 250 zapchastlari","moto tritsikl dvigateli","yuk motor 250","suvli sovutish motor","tritsikl uchun motor","moto ehtiyot qismlari ulgurji","dvigatel yetkazib beruvchi","moto motor importchi","Loncin ehtiyot qismlari","Lifan ehtiyot qismlari","Zongshen motor 250","moto motor sotib olish","tritsikl motor sotib olish","moto motor distribyutor"];
const retained=[...keywordRows("Peru",peRetained,"P4-PE-01,P4-PE-04,P4-PE-05,P4-PE-06,P4-PE-07,P4-PE-08"),...keywordRows("Uzbekistan",uzRetained,"P4-UZ-01,P4-UZ-03,P4-UZ-04,P4-UZ-05,P4-UZ-07")];
const raw=[...peRejected.map(k=>["Peru","Spanish",k,"需人工清洗的西语候选词","Rejected","N/A","","","N/A","N/A","Unknown","PROXY DATA","机械后缀组合，不保留","","Unknown","Google","","","","No","Unnatural generated combination","Policy / strategy rule","Low"]),...uzRejected.map(k=>["Uzbekistan",/[a-z]/i.test(k)&&!/[а-яё]/i.test(k)?"Uzbek (not verified)":"Russian",k,"需人工清洗的俄语/乌兹别克语候选词","Rejected","Not verified","","","N/A","N/A","Unknown","PROXY DATA","机械组合或未验证乌兹别克语，不保留","","Unknown","Google / Yandex","","","","No","Unnatural or unverified wording","Policy / strategy rule","Low"])];
await exportBook("Phase_4_Keyword_Master_v2.xlsx",[{name:"Keyword Master",headers:["Country","Language","Keyword","Chinese meaning","Keyword status","Native wording status","Product","Vehicle/application","Intent","B2B/B2C","Estimated demand level","Search-volume source","Proxy method / rationale","CPC/range","Competition","Platform","Ad group","Landing page","Landing-page action","Negative?","Negative reason","Evidence IDs","Confidence"],rows:[...retained,...raw]}]);
const negatives=[
 ["Peru","Spanish","gratis","Campaign","Free intent","Policy / strategy rule"],["Peru","Spanish","empleo","Campaign","Jobs intent","Policy / strategy rule"],["Peru","Spanish","trabajo","Campaign","Jobs intent","Policy / strategy rule"],["Peru","Spanish","salario","Campaign","Salary intent","Policy / strategy rule"],["Peru","Spanish","juguete","Campaign","Toy intent","Policy / strategy rule"],["Peru","Spanish","juego","Campaign","Game intent","Policy / strategy rule"],["Peru","Spanish","manual pdf","Campaign","Manual intent","Policy / strategy rule"],["Peru","Spanish","moto usada","Engine campaigns","Used complete motorcycle","Policy / strategy rule"],["Peru","Spanish","moto completa","Engine campaigns","Vehicle sale intent","Policy / strategy rule"],["Peru","Spanish","venta de motos","Engine campaigns","Vehicle sale intent","Policy / strategy rule"],["Peru","Spanish","reparación cerca","Engine campaigns","Local repair intent","Policy / strategy rule"],["Peru","Spanish","tutorial","Campaign","Tutorial intent","Policy / strategy rule"],["Peru","Spanish","Bajaj","CG engine ad groups only","Excluded Indian platform","Policy / strategy rule"],["Peru","Spanish","TVS","CG engine ad groups only","Excluded Indian platform","Policy / strategy rule"],["Peru","Spanish","Hero","CG engine ad groups only","Excluded Indian platform","Policy / strategy rule"],
 ["Uzbekistan","Russian","бесплатно","Campaign","Free intent","Policy / strategy rule"],["Uzbekistan","Russian","работа","Campaign","Jobs intent","Policy / strategy rule"],["Uzbekistan","Russian","вакансия","Campaign","Jobs intent","Policy / strategy rule"],["Uzbekistan","Russian","зарплата","Campaign","Salary intent","Policy / strategy rule"],["Uzbekistan","Russian","игрушка","Campaign","Toy intent","Policy / strategy rule"],["Uzbekistan","Russian","игра","Campaign","Game intent","Policy / strategy rule"],["Uzbekistan","Russian","инструкция pdf","Campaign","Manual intent","Policy / strategy rule"],["Uzbekistan","Russian","мотоцикл б/у","Engine campaigns","Used vehicle intent","Policy / strategy rule"],["Uzbekistan","Russian","ремонт рядом","Engine campaigns","Local repair intent","Policy / strategy rule"],["Uzbekistan","Russian","своими руками","Campaign","DIY intent","Policy / strategy rule"],["Uzbekistan","Russian","Bajaj","CG/cargo engine ad groups only","Excluded Indian platform","Policy / strategy rule"],["Uzbekistan","Russian","TVS","CG/cargo engine ad groups only","Excluded Indian platform","Policy / strategy rule"],["Uzbekistan","Russian","Hero","CG/cargo engine ad groups only","Excluded Indian platform","Policy / strategy rule"]
 ];
await exportBook("Phase_4_Negative_Keywords_v2.xlsx",[{name:"Negative Keywords",headers:["Country","Language","Negative keyword","Scope","Reason","Evidence IDs / rule"],rows:negatives}]);
const campaigns=[
 ["Peru","Spanish","Peru","Google Search","PE | CG200 Air-Cooled Work/Cargo","CG200 air-cooled","Commercial engine research","motor CG 200 completo; motor CG 200 carguero","Phrase/exact after data validation","No competitor bidding; research terms excluded from copy","PE Spanish + Indian-platform scoped","Technical-confirmation enquiry (not submitted)","Model A ratio only","PROXY DATA","DESIGN ONLY","NOT APPROVED","P4-PE-05,P4-PE-06,P4-PE-08"],
 ["Peru","Spanish","Peru","Google Search","PE | CG150 Air-Cooled Trimoto","CG150 air-cooled","Commercial engine research","motor CG 150 completo; motor para trimoto de carga","Phrase/exact after data validation","No competitor bidding; research terms excluded from copy","PE Spanish + Indian-platform scoped","Technical-confirmation enquiry (not submitted)","Model A ratio only","PROXY DATA","DESIGN ONLY","NOT APPROVED","P4-PE-01,P4-PE-02,P4-PE-03,P4-PE-07"],
 ["Peru","Spanish","Peru","Google Search","PE | Parts Pack","Engine parts / spares pack","Wholesale after-sales","repuestos para motor CG150; kit de repuestos para motor CG200","Phrase/exact after data validation","No competitor bidding","PE Spanish; do not block parts","Catalogue request (not submitted)","Model C ratio only","PROXY DATA","DESIGN ONLY","NOT APPROVED","P4-PE-04"],
 ["Uzbekistan","Russian","Uzbekistan","Google Search","UZ | Water-Cooled Cargo","CG150–250 water-cooled cargo","Commercial engine research","двигатель для грузового трицикла; двигатель 250 кубов для трицикла","Phrase/exact after data validation","No competitor bidding; brand terms research only","UZ Russian negatives + Indian-platform scoped","Technical-confirmation enquiry (not submitted)","Model A ratio only","PROXY DATA","DESIGN ONLY","NOT APPROVED","P4-UZ-01,P4-UZ-02,P4-UZ-05"],
 ["Uzbekistan","Russian","Uzbekistan","Yandex Search (design)","UZ | Cargo Engine Research","CG150–250 water-cooled cargo","Commercial engine research","двигатель для грузового трицикла; двигатель с водяным охлаждением","Phrase/exact after Wordstat validation","No competitor bidding; brand terms research only","UZ Russian negatives + Indian-platform scoped","Technical-confirmation enquiry (not submitted)","Model A ratio only","PROXY DATA","DESIGN ONLY","NOT APPROVED","P4-UZ-01,P4-UZ-05"],
 ["Uzbekistan","Russian","Uzbekistan","Google / Yandex Search (design)","UZ | Parts / Dealer","Engine parts / spares pack","Dealer / after-sales","запчасти для двигателя Loncin; запчасти Zongshen 250","Phrase/exact after data validation","No competitor bidding","UZ Russian; do not globally block parts","Catalogue request (not submitted)","Model C ratio only","PROXY DATA","DESIGN ONLY","NOT APPROVED","P4-UZ-03,P4-UZ-04,P4-UZ-07"],
 ["Uzbekistan","Russian","Uzbekistan","SEO / Phase 2","UZ | CG250 Air-Cooled","CG250 air-cooled","Research only","двигатель CG250; двигатель для мотоцикла 250 кубов","No paid match policy","No competitor bidding","UZ Russian","No conversion goal","No paid budget","PROXY DATA","SEO / PHASE 2","NOT APPROVED","No product-specific evidence"]
 ];
await exportBook("Phase_4_Campaign_Architecture_v2.xlsx",[{name:"Campaign Architecture",headers:["Country","Language","Geo target","Platform","Campaign","Primary product","Intent","Keyword theme","Match type policy","Competitor-term policy","Negative scope","Conversion goal","Budget model","Search-data status","Status","Launch status","Evidence IDs"],rows:campaigns}]);
const landing=[
 ["Peru","Spanish","/es/peru/ — retain; reorder content","Motores CG para trimoto y trabajo de carga","Confirme eje, montaje y sistema eléctrico antes de solicitar una oferta.","CG200 air-cooled; CG150 air-cooled; parts pack","Solicitar confirmación técnica","Hola, necesito confirmar un motor CG para [aplicación]. Indique código de motor, eje de salida, montaje y sistema eléctrico.","CG200 cargo; CG150 trimoto; parts pack","CG200 air-cooled; CG150 air-cooled; Engine parts / spares pack","Cargo trimoto; mototaxi; work motorcycle","No equivalence by displacement; confirm shaft/mounting/electrical","¿Qué código de motor tiene?; ¿Qué aplicación y carga?; ¿Qué eje y montaje?; ¿Necesita motor completo o repuestos?","Motores CG para trimoto y carga | Chixiang","Motores CG y paquetes de repuestos para aplicaciones de trabajo; confirme la configuración técnica antes de comprar.","PE CG200 → engine section; PE CG150 → trimoto section; parts → parts section","P4-PE-01,P4-PE-05,P4-PE-07","NO PRODUCTION CHANGE"],
 ["Uzbekistan","Russian first; Uzbek only after native wording validation","Recommend new /ru/uzbekistan/; keep /ru/central-asia/ as interim only","Двигатели для грузовых трициклов: техническое подтверждение перед поставкой","Проверим вал, крепления, электрику и привод до предложения двигателя.","CG150–250 water-cooled cargo; parts pack; CG250 SEO only","Запросить техническое подтверждение","Здравствуйте, требуется двигатель для [применение]. Укажите модель техники, код двигателя, вал, крепления, электрику и тип привода.","Water-cooled cargo; parts/dealer; CG250 SEO","CG150–250 water-cooled cargo; Engine parts / spares pack; CG250 air-cooled (SEO)","Cargo tricycle; after-sales parts","No Loncin equivalence claim; confirm drive/card an interface, mounting and electrical","Какая модель трицикла?; Нужен двигатель или запчасти?; Какой привод и вал?; Требуется жидкостное охлаждение?","Двигатели для грузовых трициклов | Chixiang","Техническое подтверждение двигателя для грузовой мототехники до поставки.","UZ cargo → cargo section; parts → parts section; CG250 → SEO content only","P4-UZ-01,P4-UZ-03,P4-UZ-05","NO PRODUCTION CHANGE"]
 ];
await exportBook("Phase_4_Landing_Page_Roadmap_v2.xlsx",[{name:"Landing Page Roadmap",headers:["Market","Primary language","Existing/new page action","Hero H1","Hero supporting copy","Primary product order","CTA label","WhatsApp prefill text","Form default product","Form product options","Application options","Compatibility disclaimer","FAQ questions","SEO title","Meta description","Campaign-to-section mapping","Evidence IDs","Production change status"],rows:landing}]);
const budget=[
 ["Model A — 2 countries","Peru","CG200/CG150 engines + parts","55%","Research allocation ratio only; evidence breadth","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","NOT APPROVED","P4-PE-01,P4-PE-04,P4-PE-05,P4-PE-07"],
 ["Model A — 2 countries","Uzbekistan","Water-cooled cargo + parts","45%","Research allocation ratio only; cargo vehicle signal","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","NOT APPROVED","P4-UZ-01,P4-UZ-02,P4-UZ-03"],
 ["Model B — 3 countries","Deferred","Ecuador/Tanzania","Deferred","Not researched in Batch 1","Unknown","INPUT REQUIRED","NOT TESTED","Not assessed","NOT APPROVED","Policy / strategy rule"],
 ["Model C — product line","Peru","CG air-cooled","45%","Research allocation ratio only","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","NOT APPROVED","P4-PE-05,P4-PE-07"],
 ["Model C — product line","Uzbekistan","Water-cooled cargo","40%","Research allocation ratio only","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","NOT APPROVED","P4-UZ-01,P4-UZ-02"],
 ["Model C — product line","Both","Parts / spares","15%","Research allocation ratio only","Unknown","INPUT REQUIRED","MANUAL TEST REQUIRED","Phase 3 gate FAIL","NOT APPROVED","P4-PE-04,P4-UZ-03,P4-UZ-04"]
 ];
await exportBook("Phase_4_Budget_Models_v2.xlsx",[{name:"Budget Models",headers:["Model","Country","Product line","Allocation ratio","Statement","CPC availability","Margin availability","Landing readiness","Gate constraint","Launch status","Evidence IDs"],rows:budget}]);
